### ISSUE TITLE
Worth adding alias mysql_numrows for mysql_num_rows ?

### ISSUE THREAD

**Issue by megalithicportal** [rubo77/php-mysql-fix#4]
Hello, I've been using your function to update some ancient code and I found a mysql_numrows function as an alias. Possibly worth adding

  function mysql_numrows($result){
    return mysqli_num_rows($result);
  }

after function mysql_num_rows() function?

Thanks for some handy code

**Comment by rubo77** [comment]
yes, please create a pull request that adds this

**Comment by megalithicportal** [comment]
Thanks - sorry I didn't know how to create a pull request...
