### ISSUE TITLE
Error mysqli_fetch_array()

### ISSUE THREAD

**Issue by nornagest25** [rubo77/php-mysql-fix#7]
Hi, I use php 7.4 but I receive the following fatal error:

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught TypeError: mysqli_fetch_array(): Argument #1 ($result) must be of type mysqli_result, bool given in /var/www/vhosts/test1/mysql-fix.php:12\nStack trace:\n#0 /var/www/vhosts/test1/mysql-fix.php(12): mysqli_fetch_array()\n#1 /var/www/vhosts/test1/accesso.php(24): mysql_fetch_array()\n#2 {main}\n thrown in /var/www/vhosts/test1/mysql-fix.php on line 12', referer: https://.../login.php

Can you help me?

tnx!

**Comment by rubo77** [comment]
We need some more information to help:

How did you include it? Did you use the main path?

    include_once('fix_mysql.inc.php');

what are the mysql-commands look like that throw the error?
How is the database connection controlled in your scripts?

**Comment by rubo77** [comment]
please add some code examples of the scripts at the lines from the error
