### ISSUE TITLE
Will this work with PHP 8.0?

### ISSUE THREAD

**Issue by tblazek** [rubo77/php-mysql-fix#8]
Thanks for the great work on this! Just wondering if it will still work with PHP 8.0

**Comment by rubo77** [comment]
I think it could, try it out and please report your result here ;)

**Comment by rkbi** [comment]
Recently I inherited some code only to add some features, so I can not upgrade to PDO. Found this awesome repo, so tried to run the project in my local environment with php 8, but got some errors. Any suggestion would be much appreciated.

**My environment -** 
XAMPP under Linux
PHP Version 8.0.13
MariaDB - 10.4.22-MariaDB

**Error producing (I replaced the actual directory path) -** 

Fatal error: Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, bool given in <my project directory>/temp/fix_mysql.inc.php:81 Stack trace: #0 <my project directory>/temp/fix_mysql.inc.php(81): mysqli_query(false, 'SET character_s...') #1 <my project directory>/connect.php(8): mysql_query('SET character_s...', false) #2 <my project directory>/index.php(6): include('/mnt/mxlinux/op...') #3 {main} thrown in <my project directory>/temp/fix_mysql.inc.php on line 81

**The first querie is -** 

$c = @mysql_connect("localhost",<user>, <pass>);
mysql_query("SET character_set_results = 'utf8', character_set_client = 'utf8', character_set_connection = 'utf8', character_set_database = 'utf8', character_set_server = 'utf8'", $c);

Cheers.

**Comment by rubo77** [comment]
th query is not your problem, but it seems like the database-connection variable is not corrrectly set.

Do you include the script inside another class? 

We would need more of your code, to help you.

remove the @ sign before the connection command, that suppresses error messages

**Comment by Theanglz** [comment]
tengo el mismo problema, me sale este mensaje de error:


Fatal error: Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, null given in C:\xampp8.1\htdocs\siste_nuevomun\sistema\comunes\fix_mysql.inc.php:81 Stack trace: #0 C:\xampp8.1\htdocs\siste_nuevomun\sistema\comunes\fix_mysql.inc.php(81): mysqli_query(NULL, 'select borrado ...') #1 C:\xampp8.1\htdocs\siste_nuevomun\sistema\prueba.php(5): mysql_query('select borrado ...') #2 {main} thrown in C:\xampp8.1\htdocs\siste_nuevomun\sistema\comunes\fix_mysql.inc.php on line 81

**Comment by eesheesh** [comment]
To get this to work with PHP 8.2, I had to replace these two functions:
```
  function mysql_num_rows($result){
    return mysqli_num_rows($result);
  }

  function mysql_free_result($result) {
    return mysqli_free_result($result);
  }
```

With this (to check for bool values that would cause an exception):
```
  function mysql_num_rows($result){
    return is_bool($result) ? 0 : mysqli_num_rows($result);
  }

  function mysql_free_result($result) {
    return is_bool($result) ? true : mysqli_free_result($result);
  }
```

**Comment by rubo77** [comment]
> To get this to work with PHP 8.2, I had to replace these two functions:
> 
> ```
>   function mysql_num_rows($result){
>     return mysqli_num_rows($result);
>   }
> 
>   function mysql_free_result($result) {
>     return mysqli_free_result($result);
>   }
> ```
> 
> With this (to check for bool values that would cause an exception):
> 
> ```
>   function mysql_num_rows($result){
>     return is_bool($result) ? 0 : mysqli_num_rows($result);
>   }
> 
>   function mysql_free_result($result) {
>     return is_bool($result) ? true : mysqli_free_result($result);
>   }
> ```

Great!

Can you create a PR please?

**Comment by eesheesh** [comment]
> Can you create a PR please?

Unfortunately not, because:
1. I'm not sure other changes aren't also needed, and I just "got lucky" because this was the legacy code I'm using.
2. My employer's policy doesn't allow contributing, in some cases, and I don't want to spend time checking this, sorry. Feel free to use my solution as inspiration for your own modifications.

**Comment by rubo77** [comment]
PHP 8.2 works since 32daceeb
